folder_path : "C:\\Users\\saadr\\Desktop\\data_XAI\\data\\pancreas\\pancreas"
path: "C:\\Users\\saadr\\Desktop\\data_XAI\\data\\pancreas\\pancreas\\image"
model_path: "C:\\Users\\saadr\\Desktop\\data_XAI\\models"
csv_path: "C:\\Users\\saadr\\Desktop\\data_XAI\\data\\pancreas\\pancreas\\attention_label\\results_img_PT7_factual.csv"
output_dir: "C:\\Users\\saadr\\Desktop\\data_XAI\\outputs"
shap_dir: "C:\\Users\\saadr\\Desktop\\XAI Project\\outputs\\heatmap_shap_224_44.pkl"
gradcam_file: "C:\\Users\\saadr\\Desktop\\data_XAI\\outputs\\heatmap_gradcam_224.pkl"
lime_file: "C:\\Users\\saadr\\Desktop\\data_XAI\\outputs\\lime_data.pkl"
